dd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,7 +31,7 @@ jobs:
             git pull origin main || { echo "Git pull failed! Exiting."; exit 1; }
 
             echo "Installing dependencies..."
-            npm install || { echo "npm install failed! Exiting."; exit 1; }
+            npm install || { echo "npm install failed! Exiting  .."; exit 1; }
 
             echo "Restarting PM2 app..."
             pm2 restart ${{ secrets.PM2_APP_NAME }} || pm2 start app.js --name ${{ secrets.PM2_APP_NAME }}
